schedule event data structure
garoon/garoon-dts pull request #7
Opened 2019-03-07 13:09 UTC by yokotaso

2019-03-14 05:38 UTC, youtr-s requested changes

2019-03-14 05:38 UTC, youtr-s commented on src/schedule.d.ts
> +                approvedBy: User[];
approvedByの階層はEvent直下ではなくFacilityUsageRequest[]配下です。
https://developer.cybozu.io/hc/ja/articles/115005314266#step6

2019-03-14 05:38 UTC, youtr-s commented on src/schedule.d.ts
> +                id: string;
Event内にversionプロパティがありません。
https://developer.cybozu.io/hc/ja/articles/115005314266#step1

2019-03-15 01:12 UTC, yokotaso commented on src/schedule.d.ts
> +                id: string;
実際に稼働させるとversionプロパティは存在していないです。
なので、ドキュメントが間違っている気がします。

2019-03-15 04:31 UTC, youtr-s commented on src/schedule.d.ts
> +                id: string;
そうなのですね。。。
ドキュメント作成側の方にお知らせしておきます。

2019-03-15 04:32 UTC, youtr-s approved these changes

2019-03-18 08:56 UTC, merged