Add type definition about workflow app.
garoon/garoon-dts pull request #8
Opened 2019-03-07 14:45 UTC by yokotaso

2019-03-07 15:28 UTC, teppeis commented on tsconfig.json
> +  ],
@yokotaso VS Code and users of this package needs `/// <reference />`, this config file is only for internal developers of this package.

2019-03-13 09:58 UTC, youtr-s requested changes

2019-03-13 09:58 UTC, youtr-s commented on src/workflow.d.ts
> +                type: 'DATETIME';
type の値は'DATETIME' ではなく 'ROUTE_NAVI'かと思います。

2019-03-13 09:58 UTC, youtr-s commented on src/workflow.d.ts
> +                    | 'CANCEL'[];
listで選択できる値に'CONFIRM','ACKNOWLEDGE'がありません。
https://developer.cybozu.io/hc/ja/articles/115001457503#step4

2019-03-15 04:34 UTC, youtr-s approved these changes

2019-03-18 08:56 UTC, merged